### ISSUE TITLE
Difference between different Seeed Studio GPRS libraries?

### ISSUE THREAD

**Issue by karl-petter** [Seeed-Studio/GPRSInterface#1]
Could you please add information in the readme what the difference is between all the different GPRS libraries developed by Seeed Studio?

I have found these X different implementations:
https://github.com/Seeed-Studio/GPRSInterface - this one
https://github.com/Seeed-Studio/GPRS_Shield_Suli - for the GPRS shield V2
https://github.com/Seeed-Studio/Xively_GPRS/tree/master/GPRSClient - a separate client in another project
https://github.com/Seeed-Studio/Seeeduino_GPRS -  for the shield based on the SIM800 chip

This makes it quite confusing since there is no information readily available about the differences. The three first are linked to from the GPRS Shield product page http://www.seeedstudio.com/depot/GPRS-Shield-V20-p-1379.html?cPath=19_20 so I guess these are targeted specifically for the SIM900 chip but why three different libs that seems to do the same thing? Which one should I choose?

And the final fourth is for another chip but is that chip so different? Can not that library had been merged with any of the above and just add extra functionality required by the SIM800 chip since that seems to have more features than the SIM900?

**Comment by lawliet004** [comment]
Hi, I am sorry for making your confused.  <br><br> the GPRSInterface is a library to use GPRS like Ethernet or WiFi, you can use this library to access the internet.<br><br>  GPRS Shield Suli is a library to make a call or send SMS message, <br><br>Xively_GPRS is a library totally for xively project. If you want to do a project with Xively and GPRS Shield, you can have a try with this library.<br> <br>I do not know whether you are clear enough with my explain. Any problem, feel free to contact with me, thank you~

**Comment by masalinas** [comment]
Actually I have a seeeduino gprs and I would like to use any MQTT client compatible.
my question is:

```
- Can I use GPRSInterface interface with the Seeeduino GPRS IoT panel?
- The Seeeduino GPRS IoT panel supports the standard Client.h to use the pubsubclient library from Nick O'Leary to connect this card with MQTT?
- Do you recomend other MQTT client compatible with this panel???
```

Regards
